# Base16 Zenburn 256 - alacritty color config
colors:
  primary:
    background: '0x191724'
    foreground: '0xe0def4'
  cursor:
    text: '0x191724'
    cursor: '0x796268'
  vi_mode_cursor:
    text: '0x191724'
    cursor: '0x796268'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '0x2A2738'
  normal:
    black:   '0x6e6a86'
    red:     '0xeb6f92'
    green:   '0x9ccfd8'
    yellow:  '0xf6c177'
    blue:    '0x31748f'
    magenta: '0xc4a7e7'
    cyan:    '0xebbcba'
    white:   '0xe0def4'
  bright:
    black:   '0x6e6a86'
    red:     '0xeb6f92'
    green:   '0x9ccfd8'
    yellow:  '0xf6c177'
    blue:    '0x31748f'
    magenta: '0xc4a7e7'
    cyan:    '0xebbcba'
    white:   '0xe0def4'

# Mouse
mouse:
  hide_when_typing: true

# Setup term for programs to be able to use it
env:
  TERM: alacritty

window:
  padding:
    x: 10
    y: 5
  dynamic_padding: true
  decorations: full
  # decorations: buttonless


# Sample Font configuration for font: Monoid.
# Feel free to use different font configuration family & face for each sections
font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font Mono
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 12.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing
  # I've given in 14 spacing which fits really well with my fonts, you may change it
  # to your convenience but make sure to adjust 'glyph_offset' appropriately post that
  offset:
   x: 0
   y: 0

  # Note: This requires RESTART
  # By default when you change the offset above you'll see an issue, where the texts are bottom
  # aligned with the cursor, this is to make sure they center align.
  # This offset should usually be 1/2 of the above offset-y being set.
  glyph_offset:
   x: 0
   # Keeping this as half of offset to vertically align the text in cursor
   y: 2

  # Better font rendering for mac
  use_thin_strokes: true

# Live config reload (changes require restart)
live_config_reload: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

cursor:
  style: Block
  vi_mode_style: Beam
  unfocused_hollow: true

key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }
